### ISSUE TITLE
Question about the final entropy coding

### ISSUE THREAD

**Issue by smileformylove** [liujiaheng/compression#1]
Really thank you for the code and your work!

I found there are no entropy coding to obtain the final bitstream, only the estimated bit-rates are tested. It may not be accurate for your curves in your paper!

Best regards!

**Comment by liujiaheng** [comment]
Actually, the estimated bitrates are close to the real bitrates. If you want to obtain the real bitrates, you can refer to L3C(https://github.com/fab-jul/L3C-PyTorch), which has implemented the entropy coding module well.
