### ISSUE TITLE
关于熵编码的问题

### ISSUE THREAD

**Issue by townblack** [liujiaheng/compression#10]
作者，
    您好，我注意到您的代码中并未实现熵编码，我看到其他人的提的issues中也问了类似的问题，您提到预测出来的码率和熵编码的码率很接近，不知道您是否有数据来说明？您的运行时间考虑熵编码了吗？

**Comment by ywz978020607** [comment]
同问

**Comment by ywz978020607** [comment]
recon_sigma变量没有用来恢复图像，在训练过程中被忽略了，这样和没有z网络有什么区别呀
、

**Comment by cdyrhjohn** [comment]
你去跑balle的tensorflow compression里面的模型，你会发现estimate rate和实际的rate没有太大区别。（所以，为了偷懒，很多作者通常就懒得去搞编码了）。在给定prior的情况下，通常来讲算数编码的结果基本上就趋近于于-log P(x)，这点wikipedia也有说明：In general, arithmetic coders can produce near-optimal output for any given set of symbols and probabilities (the optimal value is −log2P bits for each symbol of probability P, see source coding theorem)

**Comment by hzk7287** [comment]
> 你去跑balle的tensorflow compression里面的模型，你会发现estimate rate和实际的rate没有太大区别。（所以，为了偷懒，很多作者通常就懒得去搞编码了）。在给定prior的情况下，通常来讲算数编码的结果基本上就趋近于于-log P(x)，这点wikipedia也有说明：In general, arithmetic coders can produce near-optimal output for any given set of symbols and probabilities (the optimal value is −log2P bits for each symbol of probability P, see source coding theorem)

等于说这个码率的预测还是不准确的。换句话说用真实的熵编码应该可以得到更加准确的压缩效果。(你不引用那句话，老外可能要抓狂了 哈哈 说的啥啊~~）

**Comment by cdyrhjohn** [comment]
> > 你去跑balle的tensorflow compression里面的模型，你会发现estimate rate和实际的rate没有太大区别。（所以，为了偷懒，很多作者通常就懒得去搞编码了）。在给定prior的情况下，通常来讲算数编码的结果基本上就趋近于于-log P(x)，这点wikipedia也有说明：In general, arithmetic coders can produce near-optimal output for any given set of symbols and probabilities (the optimal value is −log2P bits for each symbol of probability P, see source coding theorem)
> 
> 等于说这个码率的预测还是不准确的。换句话说用真实的熵编码应该可以得到更加准确的压缩效果。(你不引用那句话，老外可能要抓狂了 哈哈 说的啥啊~~）

只是说严格意义上的不准确，但是实际上不会带来啥影响，姑且算个工程上的问题。但对发paper没影响 （这个很重要）。

**Comment by yifeipet** [comment]
肯定有影响，要和BPG比，该不能BPG还去计算熵？
