### ISSUE TITLE
Trained Model

### ISSUE THREAD

**Issue by khawar512** [liujiaheng/compression#11]
Dear Jiaheng Liu,

I am keep trying to reproduce result but number of iterations are too big. Thus, It takes long time on moderate GPU. I am requesting you to please give me trained model.

Kind Regards,
Khawar

**Comment by liujiaheng** [comment]
Sorry, I cannot provide pretrained model now.
You can train the model by yourself. 
Our code is easy to reimplement the results of the paper.

**Comment by khawar512** [comment]
How i produce same results of paper without attention module and GMM module? For high lambda you used   "tot_epoch": 10000000 which takes very long time.

**Comment by liujiaheng** [comment]
The "tot_epoch" is useless, only the iteration number is useful. The current code is used to produce the results of ICLR18, which I have described in the "Readme.md".
Thanks.
