### ISSUE TITLE
Dataset Information

### ISSUE THREAD

**Issue by khawar512** [liujiaheng/compression#14]
Dear Jiaheng Liu,

I want to know the name of flicker data you have used. Have you collected this dataset? .Can I upload your dataset on my google drive and share with public in GitHub repository. I will share two datasets links first your link and second link is mine. In future, it will be good if your university link breaks down and i also released and publish my code as soon as possible.

Kind Regards,
Khawar

**Comment by liujiaheng** [comment]
Sorry, this dataset is collected by our team. If our link breaks down, we will publish it on Google Drive.
