### ISSUE TITLE
Use of exponential in Synthesis_prior_net

### ISSUE THREAD

**Issue by trougnouf** [liujiaheng/compression#15]
You Synthesis_prior_net class is called as follow:
```
    def forward(self, x):
        x = self.relu1(self.deconv1(x))
        x = self.relu2(self.deconv2(x))
        return torch.exp(self.deconv3(x))
```
Why did you use the exponential function instead of ReLU ? That does not seem to be mentioned in Balle's or your paper.

**Comment by OctoberKat** [comment]
> You Synthesis_prior_net class is called as follow:
> 
> ```
>     def forward(self, x):
>         x = self.relu1(self.deconv1(x))
>         x = self.relu2(self.deconv2(x))
>         return torch.exp(self.deconv3(x))
> ```
> 
> Why did you use the exponential function instead of ReLU ? That does not seem to be mentioned in Balle's or your paper.

The same question. Waiting for your reply sincerely.

**Comment by liujiaheng** [comment]
ReLU function can lose information when parameter < 0.
This is my way to keep output>0.
If you want more accurate implementation, please refer to the official tensorflow version for details.

Thanks for your attention for my work.
