### ISSUE TITLE
Which paper is implemented here?

### ISSUE THREAD

**Issue by nk00230** [liujiaheng/compression#17]
Hi Jiaheng,

In the description of your repo it says "We first release the code for _Variational image compression with a scale hyperprior_, we will update our code to our full implementaion of our paper.". 

Could you clarify if the implementation currently released in this repo is still for _Variational image compression with a scale hyperprior_ or for your paper, ie _A Unified End-to-End Framework for Efficient Deep Image Compression_ ? Is the other one available anywhere?

Best wishes,
NK

**Comment by liujiaheng** [comment]
Currently, this is the repo for Variational image compression with a scale hyperprior.
