### ISSUE TITLE
questions about the code of your paper

### ISSUE THREAD

**Issue by wemozj** [liujiaheng/compression#2]
I can not find the code about  'A Unified End-to-End Framework for Efficient Deep Image Compression'，and attention module or decoder-side enhancement. Can you tell me where the code?
I find the implement of the "Variational image compression with a scale hyperprior,”

**Comment by liujiaheng** [comment]
The overall framework of our paper is similar to ICLR18, we first release the ICLR18 code.
After we deal with the copyright/patent of our paper, we will update our all code.
Thanks for your attention on our paper.
