### ISSUE TITLE
Training Details

### ISSUE THREAD

**Issue by salmanali96** [liujiaheng/compression#24]
On what hyperparameters did you train the model? How long does it take for the model to train?

**Comment by liujiaheng** [comment]
The hyper-params are defined in the config file (e.g., examples/example/config_high.json). The training time may be one day, and I have forgotten the accurate time.

**Comment by salmanali96** [comment]
The Flickr dataset contains almost 80,000 images, the number of epochs is about a million?
With the present settings, it won't be possible to train the model in a single day. 

Please let me know if I am missing something 

Thanks for the prompt response

**Comment by liujiaheng** [comment]
The epoch number is useless. You can just follow the iteration number.

**Comment by salmanali96** [comment]
Thank you so much 

recon_sigma has no role in creating the recon_image, it's only used to calculate the bpp value. 
Can you kindly explain to me the significance of recon_sigma in this work?
Thanks

**Comment by liujiaheng** [comment]
It is only used to estimate the bpp value. Please see the paper for more details.
