### ISSUE TITLE
Implementation  Related Question

### ISSUE THREAD

**Issue by salmanali96** [liujiaheng/compression#25]
Hello 

Just wanted to know whether this implementation is a simple autoencoder based one or not? As compressed_feature_renorm is directly fed into the encoder. We are not calculating any mean or standard deviation here.

**Comment by liujiaheng** [comment]
![image](https://user-images.githubusercontent.com/27964642/124442389-46b1ba00-ddaf-11eb-9e6b-fe8165385a8a.png)
Please see code more carefully.

**Comment by salmanali96** [comment]
On line 78 we are adding (0.5, -0.5) into the feature because of the quantization? Since the quantization scale factor was the same as well

**Comment by liujiaheng** [comment]
Yes, you can refer to the paper for more details.
