### ISSUE TITLE
Hello. Thanks to your contribution, I am getting a lot of help in studying.

### ISSUE THREAD

**Issue by herok97** [liujiaheng/compression#26]
Hello. I'm getting a lot of help in studying. 

First of all, thank you very much.

I'm writing this because there's one thing I'm confusing.

In 'compression/model.py', there is a function, feature_probs_based_sigma.

        def feature_probs_based_sigma(feature, sigma):
            mu = torch.zeros_like(sigma)
            sigma = sigma.clamp(1e-10, 1e10)
            gaussian = torch.distributions.laplace.Laplace(mu, sigma)
            probs = gaussian.cdf(feature + 0.5) - gaussian.cdf(feature - 0.5)
            total_bits = torch.sum(torch.clamp(-1.0 * torch.log(probs + 1e-10) / math.log(2.0), 0, 50))
            return total_bits, probs

In there, the 'gaussian' is defined by 'torch.distributions.laplace.Laplace'.
I don't know why you didn't define 'gaussian' by 'torch.distribution.normal.Normal'
As far as I understand, in the author's tensorflow implementation he used normal distribution.

If you don't mind, could you answer me?

Thank you again for your contribution.

**Comment by liujiaheng** [comment]
In our experiments, we find Laplace distribution can also estimate accurate bitrate. You can also try to use gaussian distribution. In our paper, we directly use the gaussian distribution.

**Comment by herok97** [comment]
I appreciate you so much :) 👍  !!!
