### ISSUE TITLE
Questions about the laplace distribution

### ISSUE THREAD

**Issue by yaoqi-zd** [liujiaheng/compression#6]
Hi jiaheng,
    I see you use laplace distribution instead of gaussian in the original ICLR2018 paper, is it because laplace is better than gaussian for univariate distribution estimation?
    so you use GMM in your full model and it's better than laplace?

**Comment by liujiaheng** [comment]
In ICLR18 paper, we find the performance of Laplace distribution is close to the single gaussian model. GMM is better than a single Gaussian and single Laplace.

**Comment by yaoqi-zd** [comment]
get it!
