### ISSUE TITLE
Is Entroypy model  not implemented？

### ISSUE THREAD

**Issue by ywz978020607** [liujiaheng/compression#9]
Hello，I noticed that your code is Balle,2018's work on Pytorch. But it doesn't have the Entropy Model Code and  code about using z to AE/AD,  In Balle's work, it is done on Tensorflow .Have you finish this part? 
Thanks for answering.

**Comment by ywz978020607** [comment]
Is recon_sigma  only used when calculating total_bits, not used to recon_image?

**Comment by liujiaheng** [comment]
You can refer to issue #1 .
